### ISSUE TITLE
After Update 1.6.1 apps slows down and crashes after reset

### ISSUE THREAD

**Issue by not-a-feature** [corona-warn-app/cwa-app-android#1676]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues/questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug
This seems to multiple bugs that may or may not be correlated.

The app was installed since day one and the risk assessment was always turned on.
### Part 1
After updating the App to version 1.6.1 the risk assessment card became slow. The grey card was shown for ca 45-60 seconds, then the green card. Sometimes I closed the app after 2 minutes after nothing was shown. 

Usually, it's immediately or takes only a few (< 3) seconds. 
Neither restarting the phone nor deleting the cache helped.
<img src="https://user-images.githubusercontent.com/25013642/99703221-212da580-2a97-11eb-9a98-e7bce0fb7fef.png" alt="Screenshot Grey card" width="200">
### Part 2
I deleted the app's data and tried to open it. The App freezes after tapping the second time on next.
It's caused by "ANR Input dispatching timed out 
```
Waiting to send non-key event because the touched window has not finished processing certain
input events that were delivered to it over 500.00ms ago.
Wait queue length: 26. Wait queue head age: 7626ms.)
```
### Part 3
Reopening was without  an issue, but after turning the risk-calculation on I got a Popup Cause: 4000, HTTP 901

### Part 4
Closing a reopening the app a time resolved all problems.

## Expected behaviour
After opening the app the green/red risk assessment card should be shown within a few seconds.

## Steps to reproduce issue  1
1. Update to 1.6.1
2. Open App
3. a) Wait for 30-45 seconds to show the green card
3. b) Wait for more than 2 minutes

## Steps to reproduce issue  2
1. Update to 1.6.1 & delete the App-data
2. Open App
3. Tap on "let's go"
4. Tap on "Next"
5 App freezes

## Steps to reproduce issue  3
1. Follow steps of issue 2
2. Open App
3. Tap on "activate risk-calculation"
4. Popup: Cause 4000, HTTP 901

## Technical details
- Mobile device: Motorola G7 Play
- Android version: LineageOS 11 based on Android 10 with the Google-Stock apps installed
- CWA: 1.6.1
- ENF: 18204217000

## Additional context
The domains *.coronawarn.app,  *.t-online.de are whitelisted. Therefore it's not directly related to #785 
I had 7 low-risk encounters in the last 14 days (I forgot to turn the app off while working)

---
Internal Tracking ID: EXPOSUREAPP-3956

**Comment by dsarkar** [comment]
Dear @not-a-feature,

Thank you for reporting these issues.
1. Can you confirm that the CWA runs without further issue now.
2. Also, can you confirm that you could reproduce your reported issues.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by not-a-feature** [comment]
1. I have no reason to think otherwise
  Neither CWA, nor the CW-Companion shows any error 
<img src="https://user-images.githubusercontent.com/25013642/99801209-edee2380-2b35-11eb-8878-5571b91dcd4d.png" alt="screenshot" width="300">

2. Each Problem could be reproduced several times

**Comment by dsarkar** [comment]
Dear @not-a-feature ,

Thanks again for your contributions.

We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-3956) in the internal Jira system. The developers will look into this issue now. Any further developments will be notified here in this Github issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @not-a-feature,

Do you experience still all the issues you have reported with CWA version 1.7.1 ?
Thanks for the feedback. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@not-a-feature,

Many thanks for the feedback and your contribution. We will close this issue now. Please don't hesitate to re-open or create a new issue, as appropriate. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by not-a-feature** [comment]
Thanks for taking a look into it.
